#ifndef _ADTERR_H
#define _ADTERR_H

typedef enum ADTErr{
		ERR_OK,
		ERR_OVERFLOW,
		ERR_ALLOC_FAIL,
		ERR_DUP_DATA,
		ERR_TO_INCREASE,
		ERR_TO_DECREASE,
		ERR_TO_REHASH,
		ERR_UNINITINALAIZED,
		ERR_UNDERFLOW,
		ERR_INDEX_OUT_OF_BOUNDS,
		ERR_EMPTY,
		ERR_SORT,
		ERR_DEAL,
		ERR_GAME_OVER	
		}ADTErr;


#endif /*_ADTERR_H*/
